analytics_legend_mapping:
  0: "Not Interested"
  1: "Unconscious"
  2: "Interested"
  3: "Competent"
  4: "Mentor"
# Hard skills param
hard_skills_grouping.clustering_skill_scaling:
  0: 0
  1: 2
  2: 3
  3: 5
  4: 6

hard_skills_grouping.hierarchical_params:
  n_clusters: 5
  metric: euclidean
  linkage: complete

hard_skills_grouping.k_means_params:
  random_state: 987
  n_clusters: 4
  max_iter: 300000  # Note: k means seems to converge very quickly in our dataset, raising it may have no impact whatsoever

hard_skills_grouping.selected_columns:
  - ID
  - R
  - Python
  - Bash
  - GIT
  - Docker
  - CLI
  - Frontend
  - SQL
  - NoSQL
  - Azure
  - AWS
  - GPC
  - PowerBI
  - Tableau
  - "Area: Time Series"
  - "Area: Classical ML"
  - "Area: NLP"
  - "Computer Vision"
  - "UxUi"
  - "Graphic design"

# Soft skills
soft_skills_grouping.clustering_skill_scaling:
  0: 0
  1: 2
  2: 3
  3: 5
  4: 6

soft_skills_grouping.hierarchical_params:
  n_clusters: 4
  metric: euclidean
  linkage: ward

soft_skills_grouping.k_means_params:
  random_state: 987
  n_clusters: 4
  max_iter: 300000  # Note: k means seems to converge very quickly in our dataset, raising it may have no impact whatsoever

soft_skills_grouping.selected_columns:
  - ID
  - "Project Management"
  - "Social Media Prom."
  - "Est. Business Relat."
  - "Est. Scientists Relat."
  - "Obt. Fin."
  - "Coop. UEW admin."
  - "HR"
